contributing.md
public/translations/cy.json
public/translations/en.json
readme.md
src/lib/i18n.ts
src/pages/[postcode]/postcode.page.tsx
src/pages/about.tsx
src/pages/error.page.tsx
src/pages/layout.tsx
src/pages/not-found.page.tsx
src/pages/start.page.tsx
src/types/i18.d.ts
welsh.html

- Google translates all Welsh content
- Adds missing translations
- Restructure translations to be based on the route structure
- Adds a Welsh example to test Welsh translations
- Adds contributor docs, for internal use, I initially was only going to add a bit about the translations but I kept thinking of more stuff to communicate

Translation organisation

---

package-lock.json
package.json
public/translations/cy.json
public/translations/en.json
src/components/control/LocationInput/LocationInput.tsx
src/components/control/MaterialSearchInput/MaterialSearchInput.tsx

Stops data lists appearing twice when all the list contains is the same text that's already inside the input.

Fix datalist appearing twice

---

index.html
src/components/canvas/ContextHeader/ContextHeader.css
src/components/canvas/ContextHeader/ContextHeader.stories.tsx
src/pages/[postcode]/material/material.layout.tsx
src/pages/[postcode]/postcode.page.tsx
src/pages/[postcode]/postcode.routes.tsx
src/pages/root.layout.tsx
src/styles/base.css

Adds a bar to the top of the material search result page showing the term that was searched for.

Search context

---

.github/mergify.yml
.github/workflows/ci.yml
.mega-linter.yml
.npmrc

Closes WRAP-268, WRAP-269, WRAP-270, WRAP-271

CI improvements

---

public/translations/cy.json
public/translations/en.json
src/components/composition/BorderedList/BorderedList.css
src/components/composition/BorderedList/BorderedList.stories.tsx
src/components/composition/BorderedList/BorderedList.tsx
src/components/control/IconLink/IconLink.css
src/components/control/MaterialSearchInput/MaterialSearchInput.tsx
src/pages/[postcode]/material/material.routes.tsx
src/pages/[postcode]/material/not-found.loader.ts
src/pages/[postcode]/material/not-found.page.tsx
src/pages/[postcode]/postcode.action.ts
src/styles/tokens/theme.css
src/types/locatorApi.ts

Adds a list of popular searches to the material not found page.

Popular searches

---

public/translations/cy.json
public/translations/en.json
src/lib/getDryContainersByMaterial.ts
src/lib/tests/getDryContainersByMaterial.test.ts
src/pages/[postcode]/material/material.loader.ts
src/pages/[postcode]/material/material.page.tsx
src/pages/[postcode]/material/material.routes.tsx
src/types/locatorApi.ts

Calls the local authority endpoint to get a list of dry schemes and containers that accept the given material to be recycled at home.

Recycle at home containers

---

src/pages/[postcode]/material/material.loader.ts
src/pages/[postcode]/material/material.page.tsx
src/types/locatorApi.ts

Call to the locations/{postcode} endpoint with the searched for material id to check if it can be recycled at a nearby place

Get locations for material query

---

public/translations/cy.json
public/translations/en.json
src/pages/[postcode]/home/home.layout.tsx
src/pages/[postcode]/home/home.loader.ts
src/pages/[postcode]/home/home.page.tsx
src/pages/[postcode]/home/home.routes.tsx

Lists a local authorities schemes on the home recycling page.
This currently only lists dry schemes until the API for grouping schemes by property type is in, a [separate issue](https://linear.app/etch/issue/WRAP-309/separate-schemes-by-property-type) has been created to update this later.

Scheme list

---

public/translations/cy.json
public/translations/en.json
src/components/composition/BorderedList/BorderedList.css
src/pages/[postcode]/home/contact.page.tsx

Contact tab content for the home recycling

Home recycling contact

---

public/translations/cy.json
public/translations/en.json
src/components/content/Icon/Icon.tsx
src/components/content/Icon/svg/external.svg
src/pages/[postcode]/home/collection.page.tsx
src/pages/[postcode]/home/home.layout.tsx
src/pages/[postcode]/home/home.routes.tsx

Setup routes and layout for the home collection page.

Collection layout

---

index.html
public/translations/cy.json
public/translations/en.json
src/components/composition/IconText/IconText.css
src/components/control/MaterialSearchInput/MaterialSearchInput.tsx
src/pages/[postcode]/home/ContainerList.tsx
src/pages/[postcode]/home/collection.page.tsx
src/pages/[postcode]/home/home.page.tsx
src/pages/[postcode]/home/recycling-centre.page.tsx
src/styles/tokens/color.css
src/styles/tokens/theme.css

Adds the search box to the recycling collection page which allows users to check whether a material is listed under one of the containers.

Bin filter

---

.github/workflows/release.yml

Move dependency install

---

.github/workflows/deploy.yml
demo/.npmrc
demo/branded.html
demo/demo-styles.css
demo/index.html
demo/index.js
demo/package-lock.json
demo/package.json
demo/vite.config.ts
demo/welsh.html
tsconfig.json

I was getting some major caching issues using jsdelivr on the demo site, so this changes to an npm install the locator and build it using vite.

Demo site cache fix

---

.github/workflows/deploy.yml

- **feat: wait for the publish action before deploying**
- **fix: install parent dependencies before running the build**

Get the preview deploy working

---

src/pages/[postcode]/home/contact.page.tsx
src/styles/base.css
src/styles/utils.css

- Adds the last updated date to the home recycling LA contact details view
- This is the only instance we have to deal with dates, so I've tried using Intl.dateFormat rather than installing another dependency
- Moves util classes to a separate CSS file.

Local Authority last updated date

---

demo/branded.html
src/components/canvas/Hero/Hero.css
src/components/canvas/IconCircle/IconCircle.css
src/components/canvas/Tip/Tip.css
src/components/content/Icon/Icon.css
src/components/control/Menu/Menu.tsx
src/components/control/PlacesMap/PlacesMap.css
src/index.tsx
src/pages/[postcode]/postcode.page.tsx
src/styles/tokens/button.css
src/styles/tokens/color.css
src/styles/tokens/theme.css

- Fixes a11y issues with colour palette ([figma](https://www.figma.com/file/Brwi52wFn3n87wIYBd9tsW/Locator?type=design&node-id=3331-15260&mode=design&t=Jy327H540RcmBbVI-4))
- Moves to preset themes for more control over the default variations
- Supports a preset theme = none in case consumers want more granular control by supplying custom CSS variables

New colours!

---

src/styles/tokens/button.css
src/styles/tokens/theme.css

Had real trouble with diamond inputs and buttons inheriting colours, not sure why will need to work this out as part of diamond.

Fix elements not inheriting theme preset

---

src/components/composition/Layout/Layout.css
src/styles/base.css

- Add a 1px border between aside and main content
- Fix the 1px scoll on the container

Global layout tweaks

---

public/translations/cy.json
public/translations/en.json
src/components/control/LocationInput/LocationInput.stories.tsx
src/components/control/LocationInput/LocationInput.tsx
src/components/control/MaterialSearchInput/MaterialSearchInput.stories.tsx
src/components/control/MaterialSearchInput/MaterialSearchInput.tsx
src/lib/useFormValidation.ts
src/pages/LocationForm.tsx
src/pages/[postcode]/home/collection.page.tsx
src/pages/[postcode]/material/search.page.tsx
src/pages/[postcode]/places/place/details.page.tsx
src/pages/[postcode]/places/place/place.page.tsx
src/pages/[postcode]/places/search/search.page.tsx
src/pages/[postcode]/postcode.page.tsx
src/styles/utils.css

Adds error messages for required material and location fields.

Form validation

---

package-lock.json
package.json
public/translations/cy.json
public/translations/en.json
src/components/content/Container/Container.css
src/components/content/Container/Container.tsx
src/components/control/Details/Details.css
src/components/control/Details/Details.tsx
src/pages/[postcode]/home/ContainerList.tsx
src/types/locatorApi.ts

- Move container notes to the bottom of the material list
- Display notes with a single line preview of the notes
- Handle new lines in notes
- Handle multiple notes in the notes array by placing 2 new lines between each array element
- Mark out residual containers so it's clear what they're there for

Reposition container notes

---

src/components/control/MaterialSearchInput/MaterialSearchInput.css
src/components/control/MaterialSearchInput/MaterialSearchInput.tsx

Couple more improvements from Jim's feedback
- Light green option hover
- More options on desktop
- Quicker submission

Material search autocomplete refinement round 2

---

demo/branded.html
demo/embed.html
demo/index.html
demo/welsh.html
index.html
public/translations/cy.json
public/translations/en.json
src/pages/LocationForm.tsx
src/pages/material.loader.ts
src/pages/material.page.tsx
src/pages/start.action.ts
src/pages/start.routes.tsx
tests/end-to-end/start.test.ts

- Adds the start view with a prefilled material which skips straight to material results after a location is entered
- Adds embed docs to the demonstration website
- More tests!

Single material embed mode

---

contributing.md
src/components/canvas/ContextHeader/ContextHeader.css
src/components/composition/Layout/Layout.css
src/components/control/PlacesMap/PlacesMap.css
src/components/control/PlacesMap/PlacesMap.tsx
src/pages/[postcode]/material/NearbyPlaces.tsx
src/pages/[postcode]/places/place/place.layout.tsx
src/pages/[postcode]/postcode.page.tsx
src/styles/base.css
standalone.html

- dvh for max height
- min main content for mobile where the map gets hidden
- fixed height layout header
- prevented scrim overlap and linked it up

Standalone variant rendering issues

---

package-lock.json
package.json
src/components/control/PlacesMap/PlacesMap.tsx
vite.config.ts

- Update sentry
- Add auth token to the vite plugin which is apparently needed for sourcemaps
- Catch map errors to stop them going to the console, it seems to mostly be internal errors in here maps which we don't have access to fix

Sentry fixes

---

src/pages/[postcode]/places/places.page.tsx

Fix for the issue shown in this video https://share.vidyard.com/watch/VF9oWX23TPD87ugUzVf42j? only happens when scrolled right to the end of the container

Fix load more scroll issue

---

public/translations/cy.json
public/translations/en.json
src/pages/[postcode]/home/collection.page.tsx

Fixes the welsh issue reported by Martin, and switches containers to bins for consistency.

Wordsmithing

---

package-lock.json
package.json
postcss.config.js
src/components/control/MaterialSearchInput/MaterialSearchInput.css

Also a small flex fix for material search input which is overflowing

Fix nested styles on samsung internet browser

---

src/lib/getContainerList.ts
src/types/locatorApi.ts
tests/mocks/localAuthority.ts
tests/unit/getContainerList.test.ts

Marked as draft until https://github.com/etchteam/recycle-locator/pull/287 merges

Handle the api removal of residual schemes

---

src/pages/[postcode]/places/places.page.tsx

- Stops sending places material search events for searches that end up erroring
- Adds PlacesList::MaterialSearch::Empty to separate valid from invalid/empty searches
- Handles locations.items coming back undefined (https://wrap.sentry.io/issues/5329698806/?alert_rule_id=15082034&alert_type=issue&notification_uuid=96340b34-64da-4370-b3f2-e36a0b939fcd&project=4506864957194240&referrer=slack)

Better handling for empty places material search

---

package-lock.json
src/lib/sortPropertyTypes.ts
src/pages/[postcode]/material/RecycleAtHome.tsx
src/pages/[postcode]/places/search/a-z.page.tsx
tsconfig.json

This will cause a sonar cloud warning but [too many people are still using Safari 15](https://wrap.sentry.io/issues/5277280655/?project=4506864957194240&query=is%3Aunresolved+toSorted&referrer=issue-stream&statsPeriod=14d&stream_index=0) and it's not worth the extra code to polyfill

Remove use of toSorted

---

.github/workflows/release.yml
package-lock.json
package.json

Also pulls in a couple of diamond UI fixes

Correct recycling locator api path

---

src/components/canvas/MapSvg/MapSvg.tsx
src/components/template/TipContent/TipContent.tsx
src/config.ts
src/index.tsx
src/lib/i18n.ts
src/pages/[postcode]/home/home.layout.tsx
src/pages/[postcode]/places/places.page.tsx
src/pages/entrypoint.tsx
src/pages/start.layout.tsx

Adds a way to configure where the public assets are served from.
I'll add proper docs for this later, in the CSP section.

Add the public path prop

---

.github/dependabot.yml

Add custom dependabot config

---

src/pages/start.action.ts

Fixes an issue where sending a null response was clearing the search params causing the next form submit to lose the data in the URL.

Fix lost search params on start page

---

public/translations/cy.json
public/translations/en.json
src/components/canvas/Hero/Hero.css
src/components/canvas/Hero/Hero.stories.tsx
src/components/canvas/Hero/Hero.tsx
src/pages/[postcode]/home/contact.page.tsx
src/pages/[postcode]/material/NotRecyclable.tsx
src/pages/[postcode]/material/material.page.tsx
src/pages/[postcode]/places/map.page.tsx
src/pages/[postcode]/postcode.page.tsx
src/styles/tokens/theme.css
tests/end-to-end/material.test.ts

WRAP-1406: Reduce heading design for non-recycables

---

public/translations/cy.json
public/translations/en.json
src/pages/[postcode]/postcode.page.tsx

- Update welsh copy for landing page improvements
- Also update explore nearby list title copy to match designs

Feature/WRAP-1355: Welsh translations

---

package-lock.json
package.json
src/components/content/Container/ContainerSVG.tsx
src/components/content/Icon/Icon.tsx
src/components/control/LocationInput/LocationInput.tsx
src/components/control/MaterialSearchInput/MaterialSearchInput.tsx
src/components/control/PlacesMap/PlacesMap.tsx
src/components/control/ReportMissingMaterial/ReportMissingMaterial.tsx
src/lib/getTip.ts
src/lib/sentry.ts
src/lib/tArray.ts
src/lib/useAnalytics.ts
src/pages/LocationForm.tsx
src/pages/[postcode]/home/error.page.tsx
src/pages/[postcode]/material/error.page.tsx
src/pages/[postcode]/material/search.loader.ts
src/pages/[postcode]/places/error.page.tsx
src/pages/[postcode]/places/place/error.page.tsx
src/pages/[postcode]/places/search/search.loader.ts
src/pages/[postcode]/postcode.page.tsx
src/pages/error.page.tsx
src/pages/material.page.tsx

Migrates to an isolated sentry to avoid polluting the global sentry state, updates Sentry, and removes a lodash function that we didn't need.

Isolate Sentry

---

public/translations/en.json
src/components/control/CardLink/CardLink.css
src/pages/refill/benefits.page.tsx
src/pages/refill/options.page.tsx
src/pages/refill/refill.page.tsx

- Updates the MVP copy feedback
- Align card links centrally so they look a bit more balanced on largest screens

WRAP-1853: MVP feedback mop up
