etchteam/recycling-locator

- .env.example
- .gitignore
- src/components/Logo/Logo.tsx
- src/config.ts
We'll need a publicly accessible url to load prod assets from consuming websites.
This could use the [base config option](https://vitejs.dev/config/shared-options.html#base) but it feels a bit magic I'd rather explicitly specify the public path each time so I know it's going to work.
Eventually, I think this URL will be set to unpkg
> Use an env for loading assets

- .env.example
- package-lock.json
- package.json
- src/components/LocationInput/LocationInput.stories.tsx
- src/components/LocationInput/LocationInput.tsx
- src/config.ts
- src/pages/Start.tsx
Adds native autosuggestion to the location field which appears after > 3 characters are entered.
https://github.com/etchteam/recycling-locator-widget/assets/5038459/0c0445f4-a48b-4427-b52b-988ec233dcd0
> Location input

- src/index.tsx
- src/lib/AppState.tsx
- src/pages/entrypoint.tsx
- src/pages/start.page.tsx
- Adds a postcode prop to the web component to allow people to skip location entry
- Wraps the app in a global app state provider, will probably use this for more stuff later
- We need to handle navigation inside the start route because that's where routeProvider will be available
> Postcode as a start route

- public/translations/cy.json
- public/translations/en.json
- src/components/content/Icon/Icon.tsx
- src/pages/start.layout.tsx
Makes the about info button appear to screen readers as a thing that expands/collapses content which is closest to what it's actually doing visually and indicates what content it's controlling.
Fixes the button not containing any label text.
> About info button accessibility

- index.html
- public/translations/cy.json
- public/translations/en.json
- src/components/canvas/ContextHeader/ContextHeader.stories.tsx
- src/components/canvas/MapSvg/MapSvg.stories.tsx
- src/components/canvas/Tip/Tip.stories.tsx
- src/components/composition/BorderedList/BorderedList.stories.tsx
- src/components/composition/Header/Header.stories.tsx
- src/components/composition/Wrap/Wrap.stories.tsx
- src/components/content/HeaderTitle/HeaderTitle.css
- src/components/content/HeaderTitle/HeaderTitle.stories.tsx
- src/components/content/HeaderTitle/HeaderTitle.tsx
- src/components/content/Icon/Icon.tsx
- src/components/content/Icon/svg/arrow-left.svg
- src/components/control/IconLink/IconLink.stories.tsx
- src/components/control/MaterialSearchInput/MaterialSearchInput.tsx
- src/pages/[postcode]/material/material.layout.tsx
- src/pages/[postcode]/material/material.page.tsx
- src/pages/[postcode]/material/material.routes.tsx
- src/pages/[postcode]/postcode.routes.tsx
- src/pages/root.layout.tsx
- Sets up the /material route for the material search result page
- Adds a new header style in the material layout
- Moves global actions to a new translation section so they aren't repeated everywhere
- Scopes all stories under the diamond structure
> Material search header

- index.html
- public/translations/cy.json
- public/translations/en.json
- src/pages/[postcode]/material/material.layout.tsx
- src/pages/[postcode]/material/material.routes.tsx
- src/pages/[postcode]/material/not-found.page.tsx
- src/pages/[postcode]/postcode.action.ts
- src/styles/base.css
Adds the material not found view.
Eventually, popular searches should also be part of this view – I'll add them in a separate PR.
It's a bit weird that this view uses the postcode form action but this view is firmly a material layout view instead of the start layout view because the user has committed to searching for a material, I could rename the postcode action but then it breaks convention, I could create a not-found.action that uses the postcode.action but that just adds code and ends up in the same place, I've left it for now and will see if any other routes break the convention if so the convention might need to change.
> Material not found view

- public/translations/cy.json
- public/translations/en.json
- src/pages/[postcode]/material/NearbyPlaces.tsx
- src/pages/[postcode]/material/error.page.tsx
- src/pages/[postcode]/material/material.routes.tsx
- src/pages/[postcode]/material/search.loader.ts
- src/pages/[postcode]/material/search.page.tsx
Creates a material result-specific error boundary to avoid resorting to the global error boundary which would make users start again from the location search.
Other updates:
- Fixes the popular searches error handling, I think the react-router `defer` caused the catch block to be ignored
- Moves "search again" to a generic action translation because we have it three times now
> Material result error boundary

- index.html
- package.json
- public/translations/cy.json
- public/translations/en.json
- src/components/composition/BorderedList/BorderedList.css
- src/pages/[postcode]/home/error.page.tsx
- src/pages/[postcode]/home/home.layout.tsx
- src/pages/[postcode]/home/home.routes.tsx
- src/pages/[postcode]/postcode.routes.tsx
- tests/end-to-end/postcode.test.ts
- tests/mocks/materials.ts
Adds an error page for home recycling, users could end up here if:
- There's an error fetching the local authority
- There's an error fetching the locations when the recycling centres tab is visited
This also moves the postcode loader to wrap all child routes so that the not found (location search) page is displayed anytime a child route is visited with an invalid postcode.
The `:first-of-type` fix is for bordered lists that are wrapped in `<nav>`...or anything else.
> Home recycling error handling

- .github/workflows/ci.yml
- contributing.md
- index.html
- public/translations/cy.json
- public/translations/en.json
- src/index.tsx
- src/lib/getStartPath.ts
- src/pages/LocationForm.tsx
- src/pages/home-recycling.page.tsx
- src/pages/not-found.page.tsx
- src/pages/root.layout.tsx
- src/pages/start.action.ts
- src/pages/start.page.tsx
- src/pages/start.routes.tsx
- src/styles/tokens/button.css
- src/types/vitest.d.ts
- tests/end-to-end/material.test.ts
- tests/end-to-end/postcode.test.ts
- tests/end-to-end/start.test.ts
- tests/unit/getStartPath.test.ts
- tests/utils/describeEndToEndTest.ts
- Adds the /home-recycling start path
- Moves the location form out to a component as it's now included on 3 paths
- Makes primary buttons bold (fixes WRAP-263)
- Removes the postcode attribute in favour of everyone using the path attribute instead. This removes the path abstraction so it's more exposed to invalid paths but avoids conflicts between which route to render based on which combination of attributes is provided so overall I think it's easier to use, document and work with
> Recycle from home start view

- contributing.md
- public/translations/cy.json
- public/translations/en.json
- src/components/canvas/Loading/Loading.css
- src/components/composition/BorderedList/BorderedList.css
- src/components/composition/IconText/IconText.css
- src/components/content/Icon/Icon.tsx
- src/components/content/Icon/svg/arrow-right.svg
- src/components/control/Details/Details.css
- src/components/control/Details/Details.stories.tsx
- src/components/control/Details/Details.tsx
- src/components/template/SchemeContainerSummary/SchemeContainerSummary.tsx
- src/lib/getPropertiesByMaterial.ts
- src/lib/getPropertyDisplayName.ts
- src/pages/[postcode]/home/ContainerList.tsx
- src/pages/[postcode]/home/collection.page.tsx
- src/pages/[postcode]/home/contact.page.tsx
- src/pages/[postcode]/home/home.layout.tsx
- src/pages/[postcode]/home/home.loader.ts
- src/pages/[postcode]/home/home.page.tsx
- src/pages/[postcode]/material/RecycleAtHome.tsx
- src/pages/[postcode]/material/material.loader.ts
- src/pages/[postcode]/material/material.page.tsx
- src/types/locatorApi.ts
- stylelint.config.cjs
- tests/end-to-end/material.test.ts
- tests/mocks/localAuthority.ts
- tests/unit/getPropertiesByMaterial.test.ts
- tests/unit/getPropertyDisplayName.test.ts
Adds support for the new Local Authority API response to allow schemes to be split up by property type.
**Sonarcloud warnings**
- Its main issue is duplication, but all the duplication comes from tests and mock data
- It's complaining that summary isn't a native interactive element so needs keyboard handlers but it is an interactive element with a role of button and the keyboard listeners are already bound
> Split home collections by property type

- .github/workflows/deploy.yml
- .github/workflows/release.yml
- src/config.ts
Fix the package version header sent to the API coming through as 0.
This will actually send the previous package version, because semantic release won't have run yet, but it's close enough.
> Fix package version header

- demo/vite.config.js
At the moment the sub-routes at https://etchteam.github.io/recycling-locator/ aren't working.
This fixes the issue using the approach outlined in the Vite docs https://vitejs.dev/guide/build#multi-page-app
> Add non-index entrypoints to demo

- .github/workflows/deploy.yml
`npm ci` is locking the locator version to what's in the package-lock, needs to update on each release.
> NPM install demo deps

- .github/workflows/deploy.yml
Marker stopped showing up on the demo site, I think it's because this env is named wrong, public envs in vite need to be prefixed vite_ as a safety measure.
> Fix marker env key name

- src/components/control/PlacesMap/PlacesMap.css
- src/components/control/PlacesMap/PlacesMap.tsx
Needed to listen to touchstart instead of click for touch devices.
Also fixes a couple of layout issues with the map:
- Avoid flush button on small screen
- Fix card overflow x axis on small screen
> Map markers not clickable on mobile

- src/styles/base.css
- tests/end-to-end/home.test.ts
- tests/end-to-end/material.test.ts
- tests/end-to-end/places.test.ts
Note: The snapshots won't update until after the next release due to the CDN public path reference for the CSS file, but it's been tested locally
> Disable animations whilst in test mode

- src/components/control/Fab/Fab.css
- src/components/control/Fab/Fab.tsx
- src/pages/[postcode]/places/places.page.tsx
- src/styles/base.css
Fixes a couple of weird Safari only rendering issues with the FAB button:
- On the list view the FAB was displaying in a random position on the page
- On the map it was disappearing when the map loaded
In both cases, the button was still clickable at the original position, so it's only the browser rendering the visual part of the button in a different place 🥴
> Fix safari fab rendering issue

- src/lib/getPropertyDisplayName.ts
- src/pages/[postcode]/home/collection.page.tsx
- src/pages/[postcode]/home/home.page.tsx
- src/pages/[postcode]/material/RecycleAtHome.tsx
- tests/unit/getPropertyDisplayName.test.ts
Avoids the potential of showing a duplicate scheme name given a non-all-properties-property-type by filtering out the schemes from the list that are included under the all properties property type.
> Fix duplicate scheme names

- src/components/composition/BorderedList/BorderedList.css
- src/components/content/PlaceSummary/PlaceSummary.css
- src/components/control/PlacesMap/PlacesMap.tsx
- src/pages/[postcode]/home/collection.page.tsx
- src/pages/[postcode]/home/home.layout.tsx
- src/pages/[postcode]/home/home.loader.ts
- src/pages/[postcode]/material/material.layout.tsx
- src/pages/[postcode]/places/map.page.tsx
- src/pages/[postcode]/places/place/place.layout.tsx
- src/pages/[postcode]/places/places.layout.tsx
- src/pages/[postcode]/places/places.page.tsx
- src/pages/[postcode]/places/search/search.layout.tsx
- [WRAP-477 : \[Marker.io\] 'Home' link](https://linear.app/etch/issue/WRAP-477/[markerio]-home-link)
- [[WRAP-492 : Popular searches – link target area](https://linear.app/etch/issue/WRAP-492/popular-searches-link-target-area)](https://linear.app/etch/issue/WRAP-492/popular-searches-link-target-area)
- [[WRAP-488 : Home Recycling – Scheme order](https://linear.app/etch/issue/WRAP-488/home-recycling-scheme-order)](https://linear.app/etch/issue/WRAP-488/home-recycling-scheme-order)
- [[WRAP-493 : Place summary – bolding is back to front](https://linear.app/etch/issue/WRAP-493/place-summary-bolding-is-back-to-front)](https://linear.app/etch/issue/WRAP-493/place-summary-bolding-is-back-to-front)
- [[WRAP-494 : Places list – tip spacing should match the …
> Minor enhancement feedback round 2

- src/index.tsx
Adds a global type for the recycling-locator custom element that's compatible with React projects (JSX)
> Fix recycling locator element type for React

- src/styles/base.css
A small fix which adds a background colour to the whole locator.
Without this, in some places, the websites background colour will leak through into the locator UI. This is only visible when the background colour isn't white (unlike the demo site).
> Fix missing background

- package.json
- src/components/composition/Layout/Layout.css
- src/components/control/MaterialCategoriesNav/MaterialCategoriesNav.css
- src/components/control/MaterialCategoriesNav/MaterialCategoriesNav.tsx
- src/lib/AppState.tsx
- src/styles/tokens/container.css
- Fixed randomUUID only exists for https so caused an error when testing locally
- Used --container-height for the standalone version to reduce the amount of conditions needed and fix the category search height on the standalone app
- Set the button colour for category nav because IOS colours it as a default browser blue otherwise
- Swapped the :has selector for an active class, IOS couldn't cope with the selector even though it's meant to support it
> Fix category nav ios issues

- public/translations/cy.json
- public/translations/en.json
- src/pages/[postcode]/places/place/place.page.tsx
Conditional display for the place details view, based on the number of material categories
- `1` category = category in title unless the category is "others" then it displays this/these items
- `<=3` categories = material lists open, search hidden
- `>3` categories = same as before – material category collapse with search
> Place details material category conditions

- src/components/control/PlacesMap/PlacesMap.tsx
- src/lib/useAnalytics.ts
- src/pages/root.layout.tsx
Fixes WRAP-599
Fixes WRAP-600
- Avoids sending a page view before the start route has loaded, this can happen quickly and cancel the in-flight request
- Removes response.json as the endpoint now always sends back a 204 with empty text (not json)
Other fixes
- getting offset of undefined errors, now ignores here maps complaining when it can't find the offset, this seems to be happening when the map isn't in view
- React router error "Deferred data for key "tip" resolved/rejected with undefined, you must resolve/reject with a value or null." `getTip` will now return null if no tip was found
> Stop the error spam

- package-lock.json
- package.json
- src/components/canvas/MapSvg/MapSvg.css
- src/components/content/Container/Container.stories.tsx
- src/components/template/SchemeContainerSummary/SchemeContainerSummary.tsx
- src/lib/sentry.ts
- src/lib/useFormValidation.ts
- src/pages/[postcode]/places/place/place.page.tsx
- src/pages/[postcode]/postcode.page.tsx
- src/pages/start.layout.tsx
- Analytics close event keeps firing so this has changed to only track opens
- Only send manual Sentry errors (that use the captureException or captureMessage) to stop capturing global errors on host sites
- Remove sentry replay recording, it's not working anyway probably because the widget shadow dom
- Handle submitter undefined in old browsers, fixes WRAP-606
- Fix input and map svg button width overflowing to more than the widgets width
- Handle postcodes that the API doesn't understand (WRAP-621)
- Fix preact duplicate key error on home recycling container summaries
> More fixes and refinements from soft launch monitoring

- src/components/control/LocationInput/LocationInput.tsx
- src/components/control/MaterialSearchInput/MaterialSearchInput.tsx
- src/components/control/PlacesMap/PlacesMap.tsx
- src/lib/getPropertiesByMaterial.ts
- src/lib/sortPropertyTypes.ts
- src/lib/useAnalytics.ts
- src/pages/[postcode]/home/recycling-centre.page.tsx
- src/pages/[postcode]/material/RecycleAtHome.tsx
- src/pages/[postcode]/places/map.page.tsx
- src/pages/[postcode]/places/places.layout.tsx
- src/pages/[postcode]/places/places.page.tsx
- src/types/locatorApi.ts
- Escape regex strings
- Avoid running regex if string is undefined
- Handle empty loader data for the places error route which shares a layout file
- Avoid uncaught errors related to the API responding with { error: 'message' } on the locations endpoint
- Handle empty la responses more gracefully by avoiding running an empty properties object through Object.keys (related to WRAP-634)
- Ignore here maps dispose errors
- Fix failed to fetch errors caused by sending an unencoded query to here maps auto-suggest endpoint, the analytics endpoint has also been encoded because the same error is appearing as coming from it
> Fix a handful of recent error reports

- src/pages/entrypoint.tsx
- src/styles/base.css
- src/styles/tokens/container.css
First load occasionally showed a flash of an unstyled icon, this removes the icon and accounts for there being no styles loaded at all and applying minimal inline styles which expects to be displayed in a flash most of the time. 
It also adds support for a container border radius customisation.
> Fix flash of unstyled icon

- public/translations/cy.json
- public/translations/en.json
- src/components/canvas/Highlight/Highlight.css
- src/components/canvas/Highlight/Highlight.stories.tsx
- src/components/canvas/Highlight/Highlight.tsx
- src/components/control/LocationInput/LocationInput.tsx
- src/pages/LocationForm.tsx
- src/pages/start.action.ts
- src/styles/tokens.css
- src/styles/tokens/checkbox.css
- Use my location checkbox for standalone app only
- Whilst the checkbox is checked location entry is disabled
- If permissions granted the app gets postcode by lat lng instead of location upon form submission
- If permissions are not granted an error state is displayed and the form reset
Sonarcloud has raised a security alert doesn't want us to include geolocation but it's completely optional convenience 
https://github.com/etchteam/recycling-locator/assets/5038459/e548b069-b567-452a-8d13-97783c35bec2
> Use current location

- public/translations/cy.json
- public/translations/en.json
- src/pages/LocationForm.tsx
- src/pages/start.action.ts
- src/styles/tokens/color.css
- src/styles/tokens/theme.css
- tests/end-to-end/start.test.ts
Adds a checkbox to the start page location form so people can open the locator in full screen standalone app mode.
This will send an empty response back to the current tab so the widget will be left as it was when the form got submitted instead of returning the usual redirect response which would double up the page view in analytics.
If the user is on Wales Recycles or is viewing the cy version of the locator this will open locator.walesrecycles.org.uk instead of locator.recyclenow.com
Note I don't know what megalinter is complaining about, none of the dependencies it's warning about have changed...
> Open standalone app in a new tab

- public/translations/cy.json
- public/translations/en.json
- src/components/control/MaterialSearchInput/MaterialSearchInput.tsx
- src/components/control/RateThisInfo/RateThisInfo.css
- src/components/control/RateThisInfo/RateThisInfo.tsx
- src/components/control/ReportMissingMaterial/ReportMissingMaterial.tsx
- src/pages/[postcode]/material/search.page.tsx
- src/pages/[postcode]/places/search/search.page.tsx
- src/pages/[postcode]/postcode.page.tsx
Sending rate this info and report a missing material as analytics events.
To aid with use of this, I've spruced up the [analytics docs](https://www.notion.so/etchteam/Analytics-0596dab639e9477bab0f9b42017c5506?pvs=4).
And added a character limit of 250 to the comment box so it won't exceed the maximum URL 2048 character limit.
The [maximum row size in BigQuery is 100mb](https://cloud.google.com/bigquery/quotas) so I assume storing the comment won't be a problem.
https://github.com/etchteam/recycling-locator/assets/5038459/298decab-c04e-4375-8b88-3e146c755ef9
> Send feedback as analytics events

- .github/workflows/release.yml
- package-lock.json
- package.json
[Second attempt](https://github.com/etchteam/recycling-locator/pull/183) to fix the [issue happening on the Github action](https://github.com/etchteam/recycling-locator/actions/runs/9420434469/job/25952469016) with semantic release.
The issue with v24 seems to be with conventional commits dependency (`/semantic-release/release-notes-generator/issues/657`) but in this case I'm installing semantic release instead to lock its version down and avoid these kinds of issues unexpectedly creeping in when we don't expect to have to deal with them.
> Fix semantic release attempt two

- src/pages/[postcode]/places/map.page.tsx
- src/pages/[postcode]/places/place/place.layout.tsx
- src/pages/[postcode]/places/places.page.tsx
Passes the query params between listing page or map to place details and back so that searches aren't lost during navigation between these views.
Includes a small refactor to pull the place details map into a separate component in order to avoid repeating the URL.
> Retain search context between places list and details

- src/pages/[postcode]/home/recycling-centre.loader.ts
This is a partial fix for finding nearby HWRCs, by increasing the limit of locations we increase the likelihood that a HWRC will be returned.
The full fix is explained in the [highlight HWRC scope](https://etchteam.notion.site/Highlight-HWRC-155603d1ca4749b08ba1b37516ac76fd?pvs=4).
> Increase limit for nearby HWRC search

- src/pages/material.page.tsx
On the material start page, users of the script installation method using the materials prop won't have a search term. This populates the term for them by finding the material based on the given category or material ID.
> Populate material search terms based on ID

- src/components/content/Icon/Icon.tsx
- src/pages/root.layout.tsx
- [null is not an object (evaluating 'document.querySelector("recycling-locator").dispatchEvent')](https://wrap.sentry.io/issues/5547727283/?referrer=slack&notification_uuid=6ba042d8-6144-4627-9452-2b43a8b2d017&alert_rule_id=12711401&alert_type=issue)
- Handled via optional coalescing
- Guess is that it could be null in some environments where document isn't defined yet
- [Unknown variable dynamic import: ./svg/undefined.svg](https://wrap.sentry.io/issues/5542649338/?referrer=slack&notification_uuid=c7345180-cb25-4490-8924-f498c58c08f9&alert_rule_id=15082034&alert_type=issue)
- Handled by returning null before the catch block if the icon is undefined
- I've run through the codebase and can't find any instances where the icon could be undefined
- Guess is that this is some kind of Safari …
> Fix dispatchEvent on undefined and missing icon alerts

- src/components/content/Icon/Icon.tsx
We're still getting the missing icon alerts that should have been fixed by https://github.com/etchteam/recycling-locator/pull/195
The prop might be coming through as a string of "undefined", so trying this additional check.
> Fix missing icon alerts, attempt 2

- src/components/canvas/MapSvg/MapSvg.css
- src/components/canvas/MapSvg/MapSvg.stories.tsx
- src/components/canvas/MapSvg/MapSvg.tsx
- src/pages/[postcode]/places/place/place.layout.tsx
- src/pages/[postcode]/postcode.page.tsx
Related issue: https://wrap.sentry.io/issues/5568127635/?alert_rule_id=12711401&alert_type=issue&notification_uuid=20b9d956-1665-4a68-83cf-df8be230b342&project=6237470&referrer=slack
In the stack trace the problem points at "images/map.svg".
I'm guessing it is because `locator-map-svg` was a shadow dom web component that Safari must initially load outside of Preact context which causes the issue because `useAppState()` would return undefined if it's not loaded inside the component tree with the AppState.Provider above it.
There's no reason for this to be a shadow dom web component, this is one of the earliest components in the app and I think there was a reason at some point but it got refactored out so its been converted to a plan Preact template + css component instead.
> Fix use of useAppState outside preact context

- src/components/content/Container/Container.tsx
Although reduced, we're still getting [the "Unknown variable dynamic import: ./svg/undefined.svg" errors](https://wrap.sentry.io/issues/5542616257/tags/?alert_rule_id=15082034&alert_type=issue&notification_uuid=a1b16f00-d162-4e31-9166-826e829cdea1&project=4506864957194240&referrer=slack)
Based on the tag, they all seem to be from the container SVG now, so I've applied the same fix to this component as was given to the icon component.
> Fix container SVG undefined

- src/pages/LocationForm.tsx
Logs errors for geolocation
Handles missing coordinates
And possibility of `submit()` throwing
> More robust Geolocation error handling

- src/components/composition/Layout/Layout.css
- src/styles/tokens/layer.css
The layout has 3 slots: header, main and aside. The search bar is a sticky element that sits inside of main, the tab nav also works this way.
The problem with it being inside main is that when the tip in the aside is tall enough to fill up the screen it pushes main out of view, so the search bar stops scrolling at the bottom of the container and has to move up off the screen with it.
This "fix" layers the header on top of the search bar so the search bar will still scroll off the screen in some scenarios, but it won't sit on top of the header whilst it's doing so which stops it looking broken.
I think this is a viable fix because there are limited scenarios where the main would run out of space – only on mobile when the tip is taller than usual so it fills the screen. Users have to scroll …
> Fix search bar sitting on top of the header

- public/translations/cy.json
- public/translations/en.json
[Martin requested](https://e.customeriomail.com/e/c/eyJlbWFpbF9pZCI6IlJJM2FCUVVBQVpGLW9MY3laeGdFaVViVF9GQXVpQT09IiwiaHJlZiI6Imh0dHBzOi8vYXBwLm1hcmtlci5pby9pLzY2NzAzNDRlMzFkNzJmNjcxMTBkNTE1MD9yZXNvdXJjZUtpbmQ9ZmVlZGJhY2tcdTAwMjZjb2RlPWV5SmhiR2NpT2lKSVV6STFOaUlzSW5SNWNDSTZJa3BYVkNKOS5leUp5WlhOdmRYSmpaVlYxYVdRaU9pSTJOamN3TXpRMFpUTXhaRGN5WmpZM01URXdaRFV4TlRBaUxDSjBZWEpuWlhSU1pYTnZkWEpqWlNJNkltWmxaV1JpWVdOcklpd2liM2R1WlhKU1pYTnZkWEpqWlZWMWFXUWlPaUkyTURnNU5tRXhaVGhpTmpBM1pqRXlOR1V5Tm1ReFl6a2lMQ0p2ZDI1bGNsSmxjMjkxY21ObFJXMWhhV3dpT2lKa1lXNUFaWFJqYUM1amJ5SXNJblJsWVcxVmRXbGtJam9pTmpBNE9UWmhNV1U0WWpZd04yWXhNalJsTWpaa01XTmhJaXdpYVdGMElqb3hOekkwTkRBMk16UTNMQ0psZUhBaU9qRTNNalV3TVRFeE5EZDkuWDZ5Z20wZXBhWDJUS1NLS1ZJbGNiXzUwbkNtOEc3V2E3VXpQQTdFNkQ0OCIsImludGVybmFsIjoiOGRkYTA1MDNlMjQyZjM4MTA2IiwibGlua19pZCI6 …
> No nearby places -> we couldn't find any nearby places

- src/components/control/MaterialSearchInput/MaterialSearchInput.tsx
Small change to the MaterialSearchInput component to ignore case when checking if the material is real.
It now does a case insensitive comparison between the queried material and the material suggestions from the API. If a matching material is found but the case doesn't match, the query value is updated to have the 'correct' capitalisation.
> fix: allow alternative cases in material search input

- contributing.md
Add instructions to the contributing docs on how to use Caddy to set up a reverse proxy to be able to use the recycle locator proxy UAT instead of running it locally.
> docs: add UAT reverse proxy instructions to contributing docs

- src/styles/base.css
The map button was attaching itself to the browser viewport instead of the locator widget.
This adds a dummy transform to create a new [containing block](https://developer.mozilla.org/en-US/docs/Web/CSS/position#fixed_positioning) so that the fixed element is forced inside.
Regarding the actual issue, I'm not exactly sure why this seemingly randomly started happening, my guess is a browser update related to shadow DOM?
> Fix map button out of position

- src/lib/AppState.tsx
- src/lib/useAnalytics.ts
- src/types/window.d.ts
Allows WRAP to override the session ID so that they can link embedded sessions with recycle now/wales recycles sessions.
Also captures the embedding path, for even more analytics power.
> Analytics tweaks

- src/components/canvas/Tip/Tip.css
- src/components/canvas/Tip/Tip.tsx
- src/components/template/TipContent/TipContent.tsx
- src/lib/LocatorApi.ts
- src/lib/getTip.ts
- src/pages/start.layout.tsx
- src/pages/start.loader.ts
- src/pages/start.page.tsx
- src/pages/start.routes.tsx
- src/types/locatorApi.ts
Adds the start page promo tip, it's got a different background and a full width image. It'll fallback to the standard image if no tip with a path of "/" is found.
This also makes proper use of the path filter on the proxy and adds support for the country filter based on the i18n.language.
> Add homepage promo tip

- .github/workflows/release.yml
- .npmrc
- scripts/get-next-version.sh
Moves the next version grabbing to a shell script and calls tty to get a usable device, which should fix the release.
Additionally adds provenance publishing to trigger a new release, and tidies up the action a little.
> Fix releases

- src/pages/start.layout.tsx
The default tip image had enough time to display when the recycling meta endpoint took a while to respond.
This changes it so an empty default green section displays first, followed by either:
- the start route tip if one is found
- the default tip if no tip is found
https://github.com/user-attachments/assets/1abec1e8-7a08-4d84-802e-54279d7f555e
> Fix flash of default tip

- src/lib/getTip.ts
Closes both [WRAP-1698](https://linear.app/etch/issue/WRAP-1698/start-page-tip-is-blank-when-clicking-change-postcode) & [WRAP-1709](https://linear.app/etch/issue/WRAP-1709/item-specific-tips-not-loading)
Issues fixed:
- WRAP-1698: Tip wasn't appearing when returning to the start page from other pages, this was because the getTipCountry call only resolved when i18n.on runs, which only runs on the first initialization
- WRAP-1709: Tips for materials weren't loading, this was fixed by the above and updating getTipCountry call to await
Also addressed:
- Seems unnecessary to re-check the country everytime, if the web address changes then the whole locator would be reload anyway, so added a saved copy of the country
- ^ If there is an issue with this approach, then !(i18n.initialised) can be …
> Fix: WRAP-1698: Fix tips not loading

- src/styles/base.css
Set left align by default to prevent page styles centering all our copy like this:
Found while investigating WRAP-1697, closes WRAP-1710.
> Force left align by default

- src/pages/[postcode]/material/material.loader.ts
`url.searchParams.get` returns `string | null`, which was causing the URL to become `/materials/null` when `materials` was not populated, leading to a 404 error being thrown.
I'm not sure if this issue was always present and has just been highlighted by the axios rollout, or if this has been caused by the axiois rollout. `fetch` seems to also 404 with the URL, so I suspect the error was just flying under the radar previously, although it seems odd that it wasn't raised.
> fix: handle missing materials

- public/translations/cy.json
- public/translations/en.json
- src/pages/refill/sign-up.page.tsx
- Fix: Make sure buttons are all translated as expected
- Feat: Detect previously submitted state so message can be translated
- Fix: Only show detailed mailchimp errors for english users - welsh get generic translated please try again message
- Fix: Wrap GDPR label in span to override diamond form label flexbox spacing issue
Extra:
- Feat: Add local storage to retain submitted form state
> Welsh translations sign-up form mop up
